name: publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/update.yml
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-site-${{ github.ref }}
  cancel-in-progress: false

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  create_nuget:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4

      - name: internal/compute-version@v1
        id: compute-version
        run: |
          $version = '1.0.${{ github.run_number }}'
          if ($env:GITHUB_REF -ne 'refs/heads/main')
          {
              $version = "$version-beta"
          }
          
          Write-Host "New version: $version"
          "package_version=$version" >> $env:GITHUB_OUTPUT

      - run: dotnet build tasks/Altemiq.DotNet.CodingStandard.Tasks --configuration Release -property:Version=${{ steps.compute-version.outputs.package_version }}

      - run: nuget pack Altemiq.DotNet.CodingStandard.nuspec -ForceEnglishOutput -Version ${{ steps.compute-version.outputs.package_version }} -Properties 'RepositoryCommit=${{ github.sha }};RepositoryBranch=${{ github.ref_name }};RepositoryUrl=${{ github.repositoryUrl }};NoWarn=NU5100;Configuration=Release'

      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 3
          path: '**/*.nupkg'
          
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - run: dotnet test tests/Altemiq.DotNet.CodingStandard.Tests/Altemiq.DotNet.CodingStandard.Tests.csproj

  deploy:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      actions: write
    needs: [create_nuget, test]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      - uses: actions/setup-dotnet@v4

      - id: push
        working-directory: ${{ env.NuGetDirectory }}
        run: |
          Write-Host "Current ref: $env:GITHUB_REF"
          dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
          dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate

      - uses: GeekyEggo/delete-artifact@v4
        if: ${{ steps.push.conclusion == 'success' }}
        with:
          name: nuget